import { expect, test } from '@playwright/test';

test('DGMT first view covers the full journey with evidence privacy and persistence', async ({ page }, testInfo) => {
  const errors: string[] = [];
  const writes: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400 && response.url().includes('/experience/')) errors.push(`${response.status()} ${response.url()}`); });
  page.on('request', request => { if (['POST', 'PATCH', 'PUT', 'DELETE'].includes(request.method())) writes.push(request.url()); });
  const checkLayout = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.goto('/experience/dgmt');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('From learning to action.');
  await expect(page.getByRole('link', { name: 'DGMT × BIS Programme Experience home' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Choose a role and explore' })).toBeVisible();
  await checkLayout();
  await page.screenshot({ path: testInfo.outputPath('dgmt-welcome.png'), fullPage: true });
  await page.getByRole('button', { name: 'Begin with Naledi' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toBeFocused();
  await page.getByLabel('What tends to start the pattern?').fill('After the fictional commute');
  await page.getByLabel('How much control does Naledi report').selectOption('3');
  await page.reload();
  await expect(page.getByLabel('What tends to start the pattern?')).toHaveValue('After the fictional commute');
  await page.getByLabel('What smaller response will Naledi try instead?').fill('');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page).toHaveURL(/#participant$/);
  await expect(page.getByLabel('What smaller response will Naledi try instead?')).toBeFocused();
  await page.getByLabel('What smaller response will Naledi try instead?').fill('Complete one field first');
  await checkLayout();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('There was no opportunity', { exact: true }).check();
  await expect(page.getByText(/in 3 of 5 opportunities/)).toBeVisible();
  await page.getByLabel('What does Naledi think the experiment revealed?').fill('PRIVATE_FICTIONAL_REFLECTION');
  await checkLayout();
  await page.getByRole('button', { name: 'See the facilitator view' }).click();
  await expect(page.getByText('PRIVATE_FICTIONAL_REFLECTION', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('table')).toBeVisible();
  await expect(page.getByRole('row', { name: /Naledi Mokoena/ })).toContainText('6 opportunities');
  await expect(page.getByText('5 opportunities · 3 smaller responses used')).toBeVisible();
  await page.getByRole('button', { name: 'Return to sharing choice' }).click();
  await page.getByLabel('Share evidence summary with facilitator', { exact: false }).check();
  await page.getByLabel('Ask for human support', { exact: false }).check();
  await page.getByRole('button', { name: 'See the facilitator view' }).click();
  await expect(page.getByText('PRIVATE_FICTIONAL_REFLECTION', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Record illustrative review', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Acknowledge support request', exact: true }).click();
  await page.getByLabel('Facilitator review note').fill('Review of the fictional shared record');
  await page.getByRole('button', { name: 'Record illustrative review', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Illustrative review recorded', exact: true })).toBeDisabled();
  await checkLayout();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByText(/rated her control 3 points higher/)).toBeVisible();
  await expect(page.getByText('Review of the fictional shared record', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByLabel('What does Naledi think the experiment revealed?').fill('REVISED_PRIVATE_REFLECTION');
  await page.getByRole('button', { name: 'See the facilitator view' }).click();
  await expect(page.getByLabel('Facilitator review note')).toHaveValue('');
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByLabel('Share evidence summary with facilitator', { exact: false }).uncheck();
  await page.getByLabel('Ask for human support', { exact: false }).uncheck();
  await page.getByRole('button', { name: 'See the facilitator view' }).click();
  await expect(page.getByText('REVISED_PRIVATE_REFLECTION', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /acknowledge support request/i })).toHaveCount(0);
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await checkLayout();
  await page.getByRole('button', { name: 'See programme outcomes' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Programme outcomes');
  await expect(page.getByText('REVISED_PRIVATE_REFLECTION', { exact: true })).toHaveCount(0);
  await expect(page.getByText('5 of 12 participants', { exact: false })).toBeVisible();
  await page.getByText('How BIS supports programme delivery', { exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Prepare a programme', exact: true })).toBeVisible();
  await checkLayout();
  await page.screenshot({ path: testInfo.outputPath('dgmt-outcomes.png'), fullPage: true });
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download illustrative report' }).click();
  expect((await download).suggestedFilename()).toBe('DGMT-BIS-Illustrative-Outcome-Report.pdf');
  await page.goBack();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Evidence profile');
  if (testInfo.project.name !== 'desktop') await page.getByRole('button', { name: 'Experience map', exact: true }).click();
  await page.getByRole('button', { name: 'Restart experience', exact: true }).click();
  await page.getByRole('button', { name: 'Keep exploring', exact: true }).click();
  await expect(page.getByText('REVISED_PRIVATE_REFLECTION', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Restart experience', exact: true }).click();
  await page.getByRole('button', { name: 'Clear and restart', exact: true }).click();
  await page.getByRole('button', { name: 'Begin with Naledi' }).click();
  await expect(page.getByLabel('What tends to start the pattern?')).toHaveValue('After arriving home from the taxi rank');
  expect(errors).toEqual([]);
  expect(writes).toEqual([]);
});

test('DGMT storage stays separate from Leap9 and recovers when unavailable', async ({ page }) => {
  await page.goto('/experience/dgmt#participant');
  await page.getByLabel('What tends to start the pattern?').fill('DGMT practice only');
  await page.goto('/experience/leap9/v2#participant');
  await expect(page.getByLabel('What tends to start the pattern?')).toHaveValue('After arriving home from the taxi rank');
  await page.getByLabel('What tends to start the pattern?').fill('Leap9 practice only');
  await page.goto('/experience/dgmt#participant');
  await expect(page.getByLabel('What tends to start the pattern?')).toHaveValue('DGMT practice only');
  await page.addInitScript(() => { Object.defineProperty(window, 'sessionStorage', { get() { throw new Error('Storage unavailable'); } }); });
  await page.reload();
  await expect(page.getByLabel('What tends to start the pattern?')).toBeVisible();
  await expect(page.getByRole('status')).toContainText('cannot keep practice answers');
  await page.getByLabel('What tends to start the pattern?').fill('An unsaved fictional cue');
  await expect(page.getByRole('status')).toContainText('could not be kept after refresh');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Real-world test');
});

test('short video plays with captions and the DGMT report contains only fixed aggregates', async ({ page, request }) => {
  await page.goto('/experience/dgmt');
  const video = page.locator('video');
  expect(await video.evaluate((element: HTMLVideoElement) => element.muted)).toBe(false);
  await video.evaluate(async (element: HTMLVideoElement) => { element.muted = true; await element.play(); });
  await expect.poll(() => video.evaluate((element: HTMLVideoElement) => element.duration)).toBeCloseTo(90, 0);
  await expect.poll(() => video.evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0);
  expect(await video.evaluate((element: HTMLVideoElement) => element.textTracks.length)).toBe(1);
  await expect.poll(() => video.evaluate((element: HTMLVideoElement & { webkitAudioDecodedByteCount?: number }) => element.webkitAudioDecodedByteCount ?? 0)).toBeGreaterThan(0);
  await video.evaluate((element: HTMLVideoElement) => element.pause());
  await page.getByText('Read the demonstration transcript', { exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Make competencies practical.' })).toBeVisible();
  const response = await request.get('/experience/dgmt/report');
  expect(response.status()).toBe(200);
  expect(response.headers()['content-type']).toBe('application/pdf');
  expect(response.headers()['cache-control']).toBe('no-store');
  expect(response.headers()['x-robots-tag']).toBe('noindex, nofollow');
  const { getDocument } = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const pdf = await getDocument({ data: new Uint8Array(await response.body()) }).promise;
  let text = '';
  for (let index = 1; index <= pdf.numPages; index++) {
    const content = await (await pdf.getPage(index)).getTextContent();
    const items = content.items.filter(item => 'str' in item);
    const body = items.map(item => item.str).join(' ');
    expect(body).toContain('ILLUSTRATIVE SIMULATION');
    for (const item of items) expect(item.transform[4] + item.width).toBeLessThanOrEqual(548);
    text += body;
  }
  expect(text).toContain('DGMT');
  expect(text).toContain('5 of 12 participants');
  expect(text).not.toMatch(/Leap9|Naledi|PRIVATE_FICTIONAL|REVISED_PRIVATE/);
  await pdf.cleanup();
});
