import {expect,test,type Page} from "@playwright/test";
const cohort={id:"group",name:"Systems class",labCode:"SYS",labVersion:"1",facilitatorEmail:"staff@local.invalid",status:"ACTIVE",startsOn:null,endsOn:null,memberIds:["learner"]};
const learner={userId:"learner",cohortId:"group",labCode:"SYS",email:"learner@local.invalid",displayName:"Test Learner",deliveryEdition:"school",mode:"FACILITATED",status:"ACTIVE",enrolment:{id:"enrolment",labVersion:"1",status:"COMPLETED",currentInvestigation:9,startedAt:"2026-01-01",updatedAt:"2026-10-01",completedAt:"2026-10-01"},experiment:null,lastActivityAt:"2026-10-01"};
const evidence={id:"evidence",lab_code:"SYS",lab_version:"1",enrolment_id:"enrolment",investigation_id:"SYS.I9",semantic_field_id:"SYS.TRANSFER",source_object_type:"RESPONSE",source_object_id:"response",provenance:"SR",value_type:"TEXT",value:'"I found the system behind the event."',status:"ACTIVE",sensitivity:"P2",occurred_at:"2026-10-01T10:00:00Z",recorded_at:"2026-10-01T10:00:00Z",prompt_label:"My systems reasoning",evidence_class:"TRANSFER",portfolio_purpose:"Track transfer",outcome:"Apply systems thinking",competency:"Systems reasoning"};
const rubric={id:"rubric",lab_code:"SYS",lab_version:"1",title:"Systems Transfer Test",task_id:"SYS.TEI09",source_reference:"BIS Volume 3 · Systems Thinking · Transfer Test",semantic_field_ids:["SYS.TRANSFER"],criteria:[{id:"C1",label:"Quality of reasoning"}],scale_min:1,scale_max:5,authored_total:true};
const base={identity:{id:"staff",email:"staff@local.invalid",displayName:"Staff"},roles:["SYSTEM_ADMIN","FACILITATOR","PROGRAMME_OWNER"],privacyBoundary:{},admin:{metrics:{learners:1,completed:1,experimentActive:0,openSafeguardingCases:0,opportunityBands:{none:1,one:0,two:0,threePlus:0}},learners:[learner],roleAssignments:[],cohorts:[cohort],labAssignments:[],supportedLabVersions:["1"],publishedLabs:[{code:"SYS",title:"Systems Thinking Lab",version:"1",runtimeMode:"DYNAMIC"}]},facilitator:{cohorts:[cohort],learners:[learner],notes:[],referrals:[]},sponsor:{cohorts:[{cohort,participantCount:5,minimumReportableCohortSize:5,suppressed:false,metrics:null,evidenceFlow:{cohortId:"group",runtimeMode:"DYNAMIC",suppressed:false,participantCount:5,totals:{recordedResponses:20,anchoredMeasures:4,startedExperiment:5,completed:5},stages:[],privacyNote:"Private wording excluded"}}]},safeguarding:null};
async function menu(page:Page,name:string){await page.getByRole("button",{name:"Open BIS menu · Staff workspace menu"}).click();await page.getByRole("dialog",{name:"Staff workspace menu"}).getByRole("link",{name,exact:false}).click();}
function checks(page:Page){const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});page.on("response",r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});return async()=>{expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);};}
test("centred staff menu separates operational tasks, preserves browser history and keyboard access",async({page})=>{
 const verify=checks(page);await page.route("**/api/staff",r=>r.fulfill({json:base}));await page.route("**/api/class-operations?**",r=>r.fulfill({json:{sessions:[],attendance:[]}}));await page.goto("/staff-shell");await expect(page.getByRole("heading",{name:"Plan and record the class"})).toBeVisible();expect(await page.locator(".staff-workspace-switcher,.facilitator-subnav").count()).toBe(0);
 await page.getByRole("button",{name:"Open BIS menu · Staff workspace menu"}).click();await expect(page.getByRole("dialog")).toBeVisible();await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("button",{name:"Open BIS menu · Staff workspace menu"})).toBeFocused();
 await menu(page,"People & access");await expect(page.getByRole("heading",{name:"Manage access"})).toBeVisible();await expect(page.getByRole("heading",{name:"Create a group"})).toBeHidden();await menu(page,"Groups & enrolment");await expect(page.getByRole("heading",{name:"Create a group"})).toBeVisible();await expect(page.getByRole("heading",{name:"Manage access"})).toBeHidden();await page.goBack();await expect(page.getByRole("heading",{name:"Manage access"})).toBeVisible();
 await menu(page,"Results overview");await expect(page.getByRole("heading",{name:"From learner evidence to programme results"})).toBeVisible();await menu(page,"Learning journey");await expect(page.getByRole("heading",{name:"Learning journey",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"From learner evidence to programme results"})).toBeHidden();await verify();
});
test("learner shares exact evidence, restores submission on refresh and revokes facilitator access",async({page})=>{
 const verify=checks(page);let shared=false,revoked=false;const bodies:Record<string,unknown>[]=[];
 await page.route("**/api/evidence-engine?**",r=>{const view=new URL(r.request().url()).searchParams.get("view");return r.fulfill({json:view==="timeline"?{records:[evidence,{...evidence,id:"private",semantic_field_id:"SYS.PRIVATE",prompt_label:"My private reflection",sensitivity:"P3",value:'"Private reflection remains mine."'}],index:{years:[2026,2021],labs:["SYS"],record_count:2}}:{groups:[{id:"group",name:"Systems class",lab_code:"SYS",lab_version:"1"}],rubrics:[rubric],submissions:shared?[{id:"submission",user_id:"learner",cohort_id:"group",title:"My transfer evidence",created_at:evidence.occurred_at,revoked_at:revoked?evidence.occurred_at:null,current:!revoked,display_name:"Test Learner",evidence:[evidence],reviews:[]}]:[]}});});
 await page.route("**/api/evidence-engine",r=>{const body=r.request().postDataJSON();bodies.push(body);if(body.action==="share")shared=true;if(body.action==="revoke")revoked=true;return r.fulfill({json:{saved:true}});});
 await page.goto("/portfolio");await expect(page.getByRole("heading",{name:"Evidence Portfolio",exact:true})).toBeVisible();await expect(page.getByRole("checkbox",{name:"Select evidence: My private reflection"})).toHaveCount(0);await page.getByRole("checkbox",{name:"Select evidence: My systems reasoning"}).check();await page.getByLabel("Submission title").fill("My transfer evidence");await page.getByRole("checkbox",{name:/I choose to share/}).check();await page.getByRole("button",{name:"Share selected evidence"}).click();await expect(page.getByRole("heading",{name:"My transfer evidence"})).toBeVisible();expect(bodies[0].evidenceIds).toEqual(["evidence"]);expect(bodies[0].cohortId).toBe("group");await page.reload();await expect(page.getByRole("heading",{name:"My transfer evidence"})).toBeVisible();await page.getByRole("button",{name:"Revoke sharing: My transfer evidence"}).click();await expect(page.getByText(/Sharing revoked/)).toBeVisible();expect(bodies[1].submissionId).toBe("submission");await verify();
});
test("facilitator uses an authored rubric, sees autosum and saves an anchored review",async({page},testInfo)=>{
 const verify=checks(page);let review:Record<string,unknown>|null=null;const submission={id:"submission",user_id:"learner",cohort_id:"group",title:"Shared systems reasoning",created_at:evidence.occurred_at,revoked_at:null,current:true,display_name:"Test Learner",evidence:[evidence],reviews:[] as unknown[]};
 await page.route("**/api/staff",r=>r.fulfill({json:base}));await page.route("**/api/evidence-engine?**",r=>r.fulfill({json:{groups:[],rubrics:[rubric],submissions:[submission]}}));await page.route("**/api/evidence-engine",r=>{review=r.request().postDataJSON();submission.reviews=[{id:"review",rubric_version_id:"rubric",disposition:"REVIEWED",feedback:review!.feedback,criterion_scores:review!.scores,supersedes_id:null,created_at:evidence.occurred_at}];return r.fulfill({json:{saved:true}});});
 await page.goto("/staff-shell?view=facilitator&section=review&group=group");await expect(page.getByText("I found the system behind the event.")).toBeVisible();await page.getByLabel("Assessment approach").selectOption("rubric");await page.getByRole("combobox",{name:"Rating",exact:true}).selectOption("4");await page.getByLabel("Evidence for this rating").fill("The response identifies the system beneath the event.");await expect(page.getByText("Total: 4 / 5",{exact:true})).toBeVisible();await page.getByLabel("Feedback for the learner").fill("You identified a system; test the relationship next.");await page.getByRole("checkbox",{name:/I have checked/}).check();await page.getByRole("button",{name:"Save review",exact:true}).click();await expect(page.getByRole("heading",{name:"No shared evidence awaiting review"})).toBeVisible();expect(review!.scores).toEqual([{criterionId:"C1",score:4,rationale:"The response identifies the system beneath the event."}]);expect(review!.expectedReviewId).toBeNull();await page.getByRole("combobox",{name:"Queue",exact:true}).selectOption("all");await expect(page.getByText("You identified a system; test the relationship next.")).toBeVisible();await page.screenshot({path:`test-results/review-${testInfo.project.name}.png`,fullPage:true});await verify();
});
test("class sessions persist and attendance requires a held class",async({page},testInfo)=>{
 const verify=checks(page);let sessions:Record<string,unknown>[]=[];const attendance:Record<string,unknown>[]=[];
 await page.route("**/api/staff",r=>r.fulfill({json:base}));await page.route("**/api/class-operations?**",r=>r.fulfill({json:{sessions,attendance}}));await page.route("**/api/class-operations",r=>{const b=r.request().postDataJSON();if(b.action==="session")sessions=[{id:"session",programme_day:b.day,session_date:b.date,status:b.status,preparation_note:b.note,updated_at:"2026-10-05T12:00:00Z"}];else attendance.push({id:"attendance",session_id:b.sessionId,learner_user_id:b.learnerId,attendance:b.attendance,recorded_at:"2026-10-05T12:00:00Z"});return r.fulfill({json:{saved:true}});});
 await page.goto("/staff-shell");await page.getByRole("combobox",{name:"Programme day",exact:true}).selectOption("3");await expect(page.getByText(/separate 90-minute Phase A/)).toBeVisible();await expect(page.getByLabel("Attendance for Test Learner")).toHaveCount(0);await page.getByLabel("Preparation and follow-up").fill("Prepare the Lab handover materials.");await page.getByLabel("Session state").selectOption("HELD");await page.getByRole("button",{name:"Save class session"}).click();await page.getByLabel("Attendance for Test Learner").selectOption("PRESENT");await expect(page.getByLabel("Attendance for Test Learner")).toHaveValue("PRESENT");await page.reload();await page.getByRole("combobox",{name:"Programme day",exact:true}).selectOption("3");await expect(page.getByLabel("Preparation and follow-up")).toHaveValue("Prepare the Lab handover materials.");await page.screenshot({path:`test-results/class-${testInfo.project.name}.png`,fullPage:true});await verify();
});
test("staff roles expose only their assigned operational destinations",async({page})=>{
 const verify=checks(page);await page.route("**/api/staff",r=>r.fulfill({json:{...base,roles:["FACILITATOR"],admin:null,sponsor:null}}));await page.route("**/api/class-operations?**",r=>r.fulfill({json:{sessions:[],attendance:[]}}));await page.goto("/staff-shell?view=admin");await expect(page.getByRole("heading",{name:"Group",exact:true})).toBeVisible();await page.getByRole("button",{name:"Open BIS menu · Staff workspace menu"}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByRole("link",{name:/Review/})).toBeVisible();await expect(dialog.getByRole("link",{name:/People & access/})).toHaveCount(0);await expect(dialog.getByRole("link",{name:/Content Studio/})).toHaveCount(0);await expect(dialog.getByRole("link",{name:/Reports/})).toHaveCount(0);await page.keyboard.press("Escape");await verify();
});
test("reports use saved-review aggregates and keep institution scope within authorised programmes",async({page})=>{
 const verify=checks(page);const queries:string[]=[];await page.route("**/api/staff",r=>r.fulfill({json:base}));await page.route("**/api/evidence-engine?**",r=>{queries.push(r.request().url());return r.fulfill({json:{cohorts:[{id:"group",name:"Systems class",participants:5,suppressed:false,reviewed_learners:3,rubrics:[{rubric_id:"rubric",title:"Systems Transfer Test",source_reference:"BIS Volume 3",sample:3,average_total:4,maximum_total:5}]}],minimum_cohort:5,minimum_cell:3,basis:"Current learner-shared evidence and saved reviews; this is assessment coverage."}});});await page.goto("/staff-shell?view=outcomes&section=reports&group=group");await expect(page.getByRole("heading",{name:"Assessment reports"})).toBeVisible();await expect(page.getByRole("cell",{name:"4 / 5"})).toBeVisible();await expect(page.getByRole("link",{name:"Download assessment report"})).toHaveAttribute("href",/cohortId=group&download=csv/);await page.getByLabel("Report scope").selectOption("institution");await expect(page.getByRole("link",{name:"Download assessment report"})).toHaveAttribute("href","/api/evidence-engine?view=report&download=csv");expect(queries.some(q=>!new URL(q).searchParams.has("cohortId"))).toBe(true);await expect(page.getByText("I found the system behind the event.")).toHaveCount(0);await verify();
});
test("portfolio separates original responses from retained calculation history",async({page})=>{
 const verify=checks(page);await page.route("**/api/evidence-engine?**",r=>{
 const view=new URL(r.request().url()).searchParams.get("view");
 return r.fulfill({json:view==="timeline"?{records:[evidence],index:{years:[2026],labs:["SYS"],record_count:1}}:view==="measureHistory"?{records:[{id:"history-1",measurement_id:"measure",enrolment_id:"enrolment",lab_code:"SYS",lab_version:"1",code:"SYS.MEASURE",label:"Transfer calculation",value:"4",status:"VALUE",evidence_strength:"LIMITED",formula_version:"SOURCE-1",source_snapshot:[{type:"RESPONSE",id:"response",role:"SYS.TRANSFER",value:evidence.value}],source_state:"VERIFIED_AT_CAPTURE",calculated_at:evidence.occurred_at,recorded_at:evidence.recorded_at}]}:{groups:[],submissions:[],rubrics:[]}});
 });await page.goto("/portfolio");await expect(page.getByRole("heading",{name:"Calculated records over time"})).toHaveCount(0);await page.getByRole("button",{name:"Review calculated records over time"}).click();await expect(page.getByRole("heading",{name:"Transfer calculation"})).toBeVisible();await expect(page.getByText("Original inputs checked when captured")).toBeVisible();await expect(page.getByRole("checkbox",{name:"Select evidence: Transfer calculation"})).toHaveCount(0);await expect(page.getByRole("checkbox",{name:"Select evidence: My systems reasoning"})).toBeVisible();await verify();
});
test("programme setup submits the published Lab plan and pending emails in one retryable request",async({page})=>{
 const verify=checks(page);const requests:Record<string,unknown>[]=[];
 await page.route("**/api/staff",r=>{if(r.request().method()==="POST")requests.push(r.request().postDataJSON());return r.fulfill({json:base});});
 await page.goto("/staff-shell?view=admin&section=groups");await page.getByLabel("Group name").fill("Systems intake");await page.getByLabel("Facilitator email").fill("facilitator@local.invalid");await page.getByLabel("Participant emails (optional)",{exact:true}).fill("first@local.invalid\npending@local.invalid");await page.getByRole("button",{name:"Create group",exact:true}).click();await expect.poll(()=>requests.length).toBe(1);expect(requests[0]).toMatchObject({action:"createCohort",name:"Systems intake",facilitatorEmail:"facilitator@local.invalid",programmeFormat:"SINGLE_LAB",labPlan:[{code:"SYS",version:"1"}],participantEmails:"first@local.invalid\npending@local.invalid"});expect(requests[0].requestKey).toMatch(/^[0-9a-f-]{36}$/);await verify();
});
