"use client";

import { BisMark } from "@/components/brand/bis-mark";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, FlaskConical, LockKeyhole, Menu, Pause, ShieldCheck, Sparkles, X } from "lucide-react";
import type { CartridgeBlock, InvestigationCartridge } from "../../lib/investigation-cartridge.mjs";

type Edition = "school" | "emerging_adult" | "workplace";
type CompiledCartridge = Omit<InvestigationCartridge, "editions"> & { edition: Edition; treatment: { label: string; audience: string; privacySummary: string } };
type Snapshot = { profile: { displayName: string; deliveryEdition: Edition }; releases: { id: string; labCode: string; contentVersion: string }[]; progress: { contentReleaseId: string; semanticStepId: string; status: string }[] };
const blockIcons: Partial<Record<CartridgeBlock["type"], typeof BookOpen>> = { story: BookOpen, system_lens: Sparkles, experiment_setup: FlaskConical, experiment_day: FlaskConical, pause: Pause };

export function InvestigationPlayer() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [cartridge, setCartridge] = useState<CompiledCartridge | null>(null); const [selected, setSelected] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); void fetch("/api/learning", { cache: "no-store", signal: controller.signal }).then(async (response) => { const data = await response.json() as Snapshot & { error?: string }; if (!response.ok) throw new Error(data.error || "Your learning record could not be loaded."); setSnapshot(data); const cartridgeResponse = await fetch(`/cartridges/habit-${data.profile.deliveryEdition}.json`, { cache: "force-cache", signal: controller.signal }); if (!cartridgeResponse.ok) throw new Error("The Habit cartridge could not be loaded."); setCartridge(await cartridgeResponse.json() as CompiledCartridge); }).catch((reason: unknown) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "The handbook could not be opened."); }); return () => controller.abort(); }, []);
  const release = snapshot?.releases.find((item) => item.labCode === "HAB");
  const completed = useMemo(() => new Set(snapshot?.progress.filter((item) => item.status === "COMPLETED" && (!release || item.contentReleaseId === release.id)).map((item) => item.semanticStepId) ?? []), [snapshot, release]);
  const session = cartridge?.sessions[selected]; const progress = cartridge ? Math.round(completed.size / cartridge.sessions.length * 100) : 0;
  async function completeSession() { if (!session || !release || saving) return; setSaving(true); setError(""); try { const response = await fetch("/api/learning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "saveProgress", labCode: "HAB", contentReleaseId: release.id, semanticStepId: session.id, status: "COMPLETED" }) }); const data = await response.json() as Snapshot & { error?: string }; if (!response.ok) throw new Error(data.error || "Progress could not be saved."); setSnapshot(data); if (cartridge && selected < cartridge.sessions.length - 1) { setSelected(selected + 1); window.scrollTo({ top: 0, behavior: "smooth" }); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Progress could not be saved."); } finally { setSaving(false); } }
  if (error && !cartridge) return <main className="learning-state"><LockKeyhole/><h1>Handbook unavailable</h1><p>{error}</p><Link href="/learning">Return to the library</Link></main>;
  if (!snapshot || !cartridge || !session) return <main className="learning-state"><span className="learning-loader"/><h1>Opening Habit Lab™…</h1><p>Matching the handbook to your learner edition.</p></main>;
  return <div className="player-shell"><header className="player-header"><button onClick={() => setMenuOpen(true)} className="player-menu" aria-label="Open investigation navigation"><Menu/></button><Link href="/learning" className="player-brand"><span><BisMark /></span><div><strong>{cartridge.title}</strong><small>{cartridge.treatment.label}</small></div></Link><div className="player-clocks"><span>Volume 1</span><strong>Investigation {session.number} of {cartridge.sessions.length}</strong>{session.phase === "EXPERIMENT" && <em>7-day experiment</em>}</div></header><div className="player-meter"><i style={{ width: `${progress}%` }}/><span>{progress}% reviewed</span></div>{menuOpen && <button className="player-scrim" onClick={() => setMenuOpen(false)} aria-label="Close navigation"/>}<aside className={`player-rail ${menuOpen ? "open" : ""}`}><div className="player-rail-top"><Link href="/learning"><ArrowLeft/>Library</Link><button onClick={() => setMenuOpen(false)} aria-label="Close investigation navigation"><X/></button></div><p>Investigation journey</p><nav aria-label="Habit investigations">{cartridge.sessions.map((item, index) => <button key={item.id} onClick={() => { setSelected(index); setMenuOpen(false); window.scrollTo({ top: 0 }); }} className={`${index === selected ? "current" : ""} ${completed.has(item.id) ? "complete" : ""}`}><span>{completed.has(item.id) ? <Check/> : item.number}</span><div><small>{item.phase}</small><strong>{item.title}</strong></div></button>)}</nav><div className="player-privacy"><ShieldCheck/><p>{cartridge.treatment.privacySummary}</p></div></aside><main className="player-main"><section className="player-mission"><p>{session.phase} · {session.duration}</p><h1>{session.title}</h1><blockquote>{session.mission}</blockquote></section><div className="player-blocks">{session.blocks.map((block) => <PlayerBlock key={block.id} block={block}/>)}</div>{error && <p className="player-error" role="alert">{error}</p>}<footer className="player-footer"><span>{session.id} · Source {cartridge.sourceTrace.sourceVersion}</span><button onClick={completeSession} disabled={saving || !release}>{saving ? "Saving…" : completed.has(session.id) ? "Reviewed" : "Mark reviewed"}<ChevronRight/></button></footer></main></div>;
}

function PlayerBlock({ block }: { block: CartridgeBlock }) { const Icon = blockIcons[block.type] || Sparkles; const stateful = block.fieldIds.length > 0; return <section className={`player-block block-${block.type}`} aria-label={block.accessibilityLabel}><div className="player-block-icon"><Icon/></div><div><p>{block.type.replaceAll("_", " ")}</p><h2>{block.title}</h2>{block.body.map((line) => <p key={line}>{line}</p>)}{stateful && <div className="player-runtime-bridge"><ShieldCheck/><div><strong>Evidence continues in the executable Lab</strong><p>This learning view explains the step. Your private response remains in the existing evidence runtime until the Habit vertical slice is connected.</p></div><Link href="/">Open Habit Lab <ArrowRight/></Link></div>}</div></section>; }

