"use client";
import {useState} from "react";
import {useEvidenceData,EvidenceState} from "./evidence-engine-client";
import type {AssessmentReport} from "@/lib/evidence-engine";
export function AssessmentReports({cohortId}:{cohortId?:string}) {
 const [institution,setInstitution]=useState(false);
 const query=`view=report${!institution&&cohortId?`&cohortId=${encodeURIComponent(cohortId)}`:""}`;
 const state=useEvidenceData<AssessmentReport>(query);
 return <section className="assessment-console"><p className="eyebrow">Evidence reporting</p><h2>Assessment reports</h2><p>Coverage and authored scores come from saved facilitator reviews of current, learner-shared evidence.</p><div className="evidence-actions">{cohortId?<label htmlFor="assessment-report-scope">Report scope <select id="assessment-report-scope" value={institution?"institution":"cohort"} onChange={e=>setInstitution(e.target.value==="institution")}><option value="cohort">Selected group</option><option value="institution">All programmes you can report on</option></select></label>:null}{state.data?<a className="evidence-button" href={`/api/evidence-engine?${query}&download=csv`}>Download assessment report</a>:null}</div><EvidenceState {...state} retry={()=>void state.load()}/>
 {state.data?<><p className="evidence-report-basis">{state.data.basis}</p>{!state.data.cohorts.length?<p>No active programmes are available for this report.</p>:state.data.cohorts.map(g=><section key={g.id} className="evidence-entry"><h3>{g.name}</h3><p>{g.participants} active learners</p>{g.suppressed?<p>Group results are hidden until there are {state.data!.minimum_cohort} learners.</p>:<><p>Reviewed learners: {g.reviewed_learners??"Hidden for privacy or not yet enough reviews"}</p>{g.rubrics.length?<div className="evidence-table-scroll" tabIndex={0} role="region" aria-label={`${g.name} rubric results`}><table className="evidence-table"><thead><tr><th scope="col">Authored rubric</th><th scope="col">Learners assessed</th><th scope="col">Mean total</th></tr></thead><tbody>{g.rubrics.map(r=><tr key={r.rubric_id}><td>{r.title}<p className="evidence-meta">{r.source_reference}</p></td><td>{r.sample}</td><td>{r.average_total===null?"No authored total":`${r.average_total} / ${r.maximum_total}`}</td></tr>)}</tbody></table></div>:<p>No rubric sample is large enough to report yet. At least {state.data!.minimum_cell} learners must contribute to a rubric result.</p>}</>}</section>)}</>:null}
 </section>;
}
