"use client";
import {useState} from "react";
import {useEvidenceData,EvidenceState} from "./evidence-engine-client";
import type {CurriculumMapping,RubricVersion} from "@/lib/evidence-engine";
import competencyFramework from "@/content/curriculum/applied-commerce/competency-framework.json";
type Template={labCode:string;title:string;task:string;source:string;scaleMin:number;scaleMax:number;authoredTotal:boolean;criteria:Array<{id:string;label:string}>};
type Governance={mappings:CurriculumMapping[];rubrics:RubricVersion[];templates:Template[]};
const competencyOptions=competencyFramework.competencies;
function canonicalCompetency(value:string|null|undefined) {
 const token=String(value??"").trim().toLowerCase();
 return competencyOptions.find(item=>item.id.toLowerCase()===token||item.title.toLowerCase()===token)?.id??"";
}
function MappingForm({mapping,saving,act}:{mapping:CurriculumMapping;saving:boolean;act:(body:Record<string,unknown>)=>Promise<boolean>}) {
 const [evidenceClass,setClass]=useState(mapping.evidence_class==="UNCLASSIFIED"?"":mapping.evidence_class),[purpose,setPurpose]=useState(mapping.classification_status==="APPROVED"?mapping.portfolio_purpose:""),[outcome,setOutcome]=useState(mapping.outcome??""),[competency,setCompetency]=useState(canonicalCompetency(mapping.competency)),[source,setSource]=useState(mapping.classification_status==="APPROVED"?mapping.source_reference:""),[checked,setChecked]=useState(false);
 return <form className="evidence-form" onSubmit={e=>{e.preventDefault();void act({action:"map",previousId:mapping.id,evidenceClass,purpose,outcome,competency,source});}}><h3>{mapping.prompt_label}</h3><p className="evidence-meta">{mapping.semantic_field_id} · {mapping.lab_code} {mapping.lab_version} · {mapping.classification_status==="APPROVED"?"Source mapping approved":"Meaning needs source review"}</p><label>Evidence purpose<select required value={evidenceClass} onChange={e=>setClass(e.target.value)} disabled={saving}><option value="">Choose the authored purpose</option>{["BASELINE","CONTEXT","PREDICTION","PLAN","OBSERVATION","OUTCOME","INTERPRETATION","TRANSFER","LEARNING_CHECK","SUPPORT_SIGNAL"].map(c=><option key={c} value={c}>{c.toLowerCase().replaceAll("_"," ")}</option>)}</select></label><label>Portfolio purpose<textarea required maxLength={1000} value={purpose} onChange={e=>setPurpose(e.target.value)} disabled={saving}/></label><label>Authored outcome<input required maxLength={1000} value={outcome} onChange={e=>setOutcome(e.target.value)} disabled={saving}/></label><label>BIS development area<select required value={competency} onChange={e=>setCompetency(e.target.value)} disabled={saving}><option value="">Choose the source-backed development area</option>{competencyOptions.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Source reference<textarea required maxLength={2000} value={source} onChange={e=>setSource(e.target.value)} disabled={saving}/></label><label className="assessment-acknowledgement"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={saving}/><span>I checked this classification, outcome and development area against the authored source.</span></label><button type="submit" disabled={saving||!checked||!evidenceClass||!purpose.trim()||!outcome.trim()||!competency.trim()||!source.trim()}>{saving?"Saving…":"Approve source mapping"}</button></form>;
}
export function AssessmentGovernance() {
 const state=useEvidenceData<Governance>("view=admin");
 const [lab,setLab]=useState(""),[version,setVersion]=useState(""),[selectedId,setSelectedId]=useState(""),[filter,setFilter]=useState("pending"),[search,setSearch]=useState(""),[fields,setFields]=useState<string[]>([]),[checked,setChecked]=useState(false);
 const mappings=state.data?.mappings??[],labs=[...new Set(mappings.map(m=>m.lab_code))].sort(),activeLab=labs.includes(lab)?lab:labs[0]??"",versions=[...new Set(mappings.filter(m=>m.lab_code===activeLab).map(m=>m.lab_version))],activeVersion=versions.includes(version)?version:versions[0]??"";
 const candidates=mappings.filter(m=>m.lab_code===activeLab&&m.lab_version===activeVersion),visible=candidates.filter(m=>(filter==="all"||m.classification_status!=="APPROVED")&&`${m.prompt_label} ${m.semantic_field_id}`.toLowerCase().includes(search.toLowerCase())),selected=visible.find(m=>m.id===selectedId)??visible[0],template=state.data?.templates.find(t=>t.labCode===activeLab),approved=candidates.filter(m=>m.classification_status==="APPROVED");
 return <section className="assessment-console"><p className="eyebrow">Assessment governance</p><h2>Curriculum evidence and rubrics</h2><p>Each captured field keeps a task and portfolio context. Approve the source-backed evidence purpose, outcome and BIS development area before using it for assessment or development reporting.</p><EvidenceState {...state} retry={()=>void state.load()}/>{state.data?<><div className="assessment-summary"><div><strong>{mappings.length}</strong><span>Mapped curriculum fields</span></div><div><strong>{mappings.filter(m=>m.classification_status==="APPROVED").length}</strong><span>Source classifications approved</span></div><div><strong>{state.data.rubrics.length}</strong><span>Immutable rubric versions</span></div></div><div className="evidence-filters"><label>Lab<select value={activeLab} onChange={e=>{setLab(e.target.value);setFields([]);setChecked(false);}}>{labs.map(l=><option key={l}>{l}</option>)}</select></label><label>Curriculum version<select value={activeVersion} onChange={e=>{setVersion(e.target.value);setFields([]);setChecked(false);}}>{versions.map(v=><option key={v}>{v}</option>)}</select></label><label>Mapping status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Needs source review</option><option value="all">All mappings</option></select></label><label>Find a question<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {!mappings.length?<p>No curriculum fields are registered yet. Published Lab prompts and captured workbook fields appear here.</p>:<div className="assessment-master"><nav className="assessment-queue" aria-label="Curriculum mapping queue">{visible.slice(0,100).map(m=><button type="button" key={m.id} aria-current={selected?.id===m.id} onClick={()=>setSelectedId(m.id)}><strong>{m.prompt_label}</strong><small>{m.classification_status==="APPROVED"?"Approved":"Needs source review"}</small></button>)}{visible.length>100?<p>Showing the first 100 fields. Use search to narrow the list.</p>:null}{!visible.length?<p>No fields match this filter.</p>:null}</nav>{selected?<MappingForm key={selected.id} mapping={selected} saving={state.saving} act={state.act}/>:null}</div>}
 <section className="evidence-entry"><h3>Enable an authored rubric</h3>{template?<form className="evidence-form" onSubmit={async e=>{e.preventDefault();if(await state.act({action:"rubric",templateCode:activeLab,labVersion:activeVersion,evidenceFields:fields})){setFields([]);setChecked(false);}}}><p>{template.title}</p><p className="evidence-meta">{template.source} · Each criterion {template.scaleMin}–{template.scaleMax} · Total / {template.criteria.length*template.scaleMax}</p><ol>{template.criteria.map(c=><li key={c.id}>{c.label}</li>)}</ol><fieldset><legend>Select the approved fields for this transfer task</legend>{approved.length?approved.map(m=><label key={m.id} className="assessment-acknowledgement"><input type="checkbox" checked={fields.includes(m.semantic_field_id)} disabled={state.saving} onChange={e=>{setFields(e.target.checked?[...fields,m.semantic_field_id]:fields.filter(f=>f!==m.semantic_field_id));setChecked(false);}}/><span>{m.prompt_label}<small className="evidence-meta"> · {m.evidence_class.toLowerCase()}</small></span></label>):<p>Approve the transfer-task fields against the source first.</p>}</fieldset><label className="assessment-acknowledgement"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={state.saving}/><span>These selected fields contain the authored transfer task assessed by this rubric.</span></label><button disabled={state.saving||!fields.length||!checked} type="submit">{state.saving?"Saving…":"Enable rubric for this curriculum version"}</button></form>:<p>The supplied sources do not define a scored transfer rubric for this Lab. Facilitators can give evidence-based feedback without a score.</p>}</section>
 <section className="evidence-entry"><h3>Enabled rubric versions</h3>{state.data.rubrics.length?state.data.rubrics.map(r=><div key={r.id}><strong>{r.title}</strong><p className="evidence-meta">{r.lab_code} {r.lab_version} · {r.semantic_field_ids.length} evidence fields · {r.source_reference}</p></div>):<p>No rubric has been enabled yet.</p>}</section></>:null}</section>;
}
