"use client";
import { readClientResponse, clientResponseMessage } from "@/lib/client-response";
import {useCallback,useEffect,useRef,useState} from "react";
const touchpoints=["Create relevance and introduce the problem","Build the first mental model","Prepare for the Lab handover","Interpret what the Lab revealed","Build the learner’s personal model","Apply the model in real life","Diagnose what happened","Introduce the final major conceptual layer","Integrate the whole model","Demonstrate change and transfer forward"];
type Session={id:string;programme_day:number;session_date:string;status:string;preparation_note:string;updated_at:string};
type Attendance={id:string;session_id:string;learner_user_id:string;attendance:string;recorded_at:string};
type Snapshot={sessions:Session[];attendance:Attendance[]};
function ClassSessionForm({current,saving,save,cohortId,day,date}:{current?:Session;saving:boolean;save:(body:Record<string,unknown>)=>Promise<void>;cohortId:string;day:number;date:string}) {
 const [note,setNote]=useState(current?.preparation_note??""),[status,setStatus]=useState(current?.status??"PLANNED");
 return <form className="evidence-form" onSubmit={e=>{e.preventDefault();void save({action:"session",cohortId,day,date,status,note,expected:current?.updated_at??null});}}><label htmlFor="class-session-status">Session state<select id="class-session-status" value={status} disabled={saving} onChange={e=>setStatus(e.target.value)}><option value="PLANNED">Planned</option><option value="HELD">Held</option><option value="CANCELLED">Cancelled</option></select></label><label>Preparation and follow-up<textarea maxLength={2000} value={note} disabled={saving} onChange={e=>setNote(e.target.value)} placeholder="Materials, class plan and factual follow-up. Keep private learner responses and safeguarding details in their own workflows."/></label><button type="submit" disabled={saving||!date}>{saving?"Saving…":"Save class session"}</button></form>;
}
export function FacilitatorClassOperations({cohortId,participants}:{cohortId:string;participants:Array<{userId:string;displayName:string}>}) {
 const [data,setData]=useState<Snapshot|null>(null),[day,setDay]=useState(1),[date,setDate]=useState(()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Johannesburg",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),writing=useRef(false),sequence=useRef(0);
 const load=useCallback(async(signal?:AbortSignal)=>{
  const request=++sequence.current;setLoading(true);setError("");
  try{const response=await fetch(`/api/class-operations?cohortId=${encodeURIComponent(cohortId)}`,{cache:"no-store",signal});const result=await readClientResponse<Snapshot>(response,"Class records are unavailable. Try again.",value=>Array.isArray(value.sessions)&&Array.isArray(value.attendance));if(request===sequence.current&&!signal?.aborted)setData(result);}
  catch(cause){if(request===sequence.current&&!signal?.aborted){setData(null);setError(clientResponseMessage(cause,"Class records are unavailable. Try again."));}}
  finally{if(request===sequence.current&&!signal?.aborted)setLoading(false);}
 },[cohortId]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 const current=data?.sessions.find(s=>s.programme_day===day&&s.session_date===date);
 async function save(body:Record<string,unknown>){
  if(writing.current)return;writing.current=true;setSaving(true);setError("");setMessage("");++sequence.current;
  try{const response=await fetch("/api/class-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await readClientResponse(response,"The class update could not be saved. Try again.");setMessage("Class record saved.");await load();}
  catch(cause){setError(clientResponseMessage(cause,"The class update could not be saved. Try again."));}
  finally{writing.current=false;setSaving(false);}
 }
 function chooseSession(s:Session){setDay(s.programme_day);setDate(s.session_date);setMessage("");}
 return <section className="assessment-console class-operations"><p className="eyebrow">Class delivery</p><h2>Plan and record the class</h2><p>Keep the facilitated touchpoint, class preparation and attendance together. Attendance is an operational record; it does not establish learning or capability.</p>{loading?<p role="status">Loading class records…</p>:null}{error?<div className="error-banner" role="alert"><p>{error}</p><button type="button" onClick={()=>void load()}>Refresh class records</button></div>:null}{message?<p role="status">{message}</p>:null}
 {data?<><div className="evidence-filters"><label htmlFor="class-programme-day">Programme day<select id="class-programme-day" value={day} disabled={saving} onChange={e=>{setDay(Number(e.target.value));}}>{touchpoints.map((_,i)=><option key={i} value={i+1}>Day {i+1}</option>)}</select></label><label>Class date<input type="date" value={date} disabled={saving} onChange={e=>{setDate(e.target.value);}}/></label></div><div className="class-purpose"><h3>Day {day}: {touchpoints[day-1]}</h3><p>Facilitated learning: 45 minutes.{day===3?" The live Lab handover leads into a separate 90-minute Phase A experience.":day===10?" Protect time for demonstration, post-measure, reflection, evidence, commitment and transfer.":" Use the learner experience and authored handbook for this touchpoint."}</p></div>{current?<p>Saved session: {current.status.toLowerCase()}</p>:null}<ClassSessionForm key={`${day}:${date}:${current?.updated_at??"new"}`} current={current} saving={saving} save={save} cohortId={cohortId} day={day} date={date}/>
 {current?.status==="HELD"?<section><h3>Class attendance</h3><div className="class-roster">{participants.map(p=>{const latest=data.attendance.find(a=>a.session_id===current.id&&a.learner_user_id===p.userId);return <label key={p.userId}><span>{p.displayName}</span><select aria-label={`Attendance for ${p.displayName}`} value={latest?.attendance??"UNKNOWN"} disabled={saving} onChange={e=>void save({action:"attendance",sessionId:current.id,learnerId:p.userId,attendance:e.target.value,expected:latest?.id??null})}><option value="UNKNOWN">Not recorded</option><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="EXCUSED">Excused</option></select></label>;})}</div></section>:<p>Mark the session as held before recording attendance.</p>}
 <details className="class-history"><summary>Saved class sessions ({data.sessions.length})</summary>{data.sessions.length?data.sessions.map(s=><button type="button" key={s.id} className="secondary" disabled={saving} onClick={()=>chooseSession(s)}>{s.session_date} · Day {s.programme_day} · {s.status.toLowerCase()}</button>):<p>No sessions have been saved yet.</p>}</details></>:null}</section>;
}
