export const LAB_VERSION = "4.5.2";
export const POLICY_VERSION = "BIS-PRIVACY-MVP-1.0";

export const baselineItems = [
  ["HAB.BASELINE.PROCRASTINATION", "Procrastinate on important tasks"],
  ["HAB.BASELINE.IMPULSE_BUYING", "Impulse buy things you don't need"],
  ["HAB.BASELINE.LATE_SLEEP", "Stay up too late when you should sleep"],
  ["HAB.BASELINE.MISSED_COMMITMENTS", "Miss deadlines or commitments"],
  ["HAB.BASELINE.GIVE_UP", "Give up quickly when things get hard"],
  ["HAB.BASELINE.UNFINISHED_PROJECTS", "Start projects but never finish them"],
  ["HAB.BASELINE.PHONE_CHECKING", "Check your phone when bored or anxious"],
  ["HAB.BASELINE.EATING_NOT_HUNGRY", "Eat when not hungry"],
  ["HAB.BASELINE.STRESS_REACTION", "Snap at people when stressed"],
  ["HAB.BASELINE.SKIP_SELF_CARE", "Skip exercise or self-care"],
] as const;

export const responseScale = ["Never", "Rarely", "Sometimes", "Often", "Always"];

export const fieldRegistry = {
  "HAB.CONTROL.PRE": { promptId: "HAB.BASE.CONTROL.01", investigation: 0, sensitivity: "P2", type: "INTEGER" },
  "HAB.STORY1.PREDICTION": { promptId: "HAB.I1.PREDICTION.01", investigation: 1, sensitivity: "P1", type: "TEXT" },
  "HAB.PATTERN.TARGET": { promptId: "HAB.I2.PATTERN.01", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.EVIDENCE.INITIAL": { promptId: "HAB.I2.EVIDENCE.01", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.EVIDENCE.INITIAL_MEANING": { promptId: "HAB.I2.EVIDENCE.02", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.REWARD.OBVIOUS": { promptId: "HAB.I2.REWARD.01", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.REWARD.LESS_OBVIOUS": { promptId: "HAB.I2.REWARD.02", investigation: 2, sensitivity: "P3", type: "TEXT" },
  "HAB.I2.OBSERVER.TEXT": { promptId: "HAB.I2.OBSERVER.01", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.I2.INSIGHT.TEXT": { promptId: "HAB.I2.INSIGHT.01", investigation: 2, sensitivity: "P2", type: "TEXT" },
  "HAB.STORY1.CORRECT": { promptId: "HAB.I3.PREDICTION_CHECK.01", investigation: 3, sensitivity: "P1", type: "BOOLEAN" },
  "HAB.STORY1.ASSUMPTION": { promptId: "HAB.I3.ASSUMPTION.01", investigation: 3, sensitivity: "P2", type: "TEXT" },
  "HAB.CUE.TEXT": { promptId: "HAB.I4.CUE.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.CUE.CERTAINTY": { promptId: "HAB.I4.CUE.CERTAINTY.01", investigation: 4, sensitivity: "P2", type: "INTEGER" },
  "HAB.ROUTINE.TEXT": { promptId: "HAB.I4.ROUTINE.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.REWARD.CERTAINTY": { promptId: "HAB.I4.REWARD.CERTAINTY.01", investigation: 4, sensitivity: "P2", type: "INTEGER" },
  "HAB.COST.TEXT": { promptId: "HAB.I4.COST.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.AFFECTED_PEOPLE.TEXT": { promptId: "HAB.I4.PEOPLE.01", investigation: 4, sensitivity: "P3", type: "TEXT" },
  "HAB.ENVIRONMENT.TEXT": { promptId: "HAB.I4.ENVIRONMENT.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.ALTERNATIVE.TEXT": { promptId: "HAB.I4.ALTERNATIVE.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.EMOTION.TEXT": { promptId: "HAB.I4.EMOTION.01", investigation: 4, sensitivity: "P3", type: "TEXT" },
  "HAB.SOCIAL_TRIGGER.TEXT": { promptId: "HAB.I4.PERSON.01", investigation: 4, sensitivity: "P3", type: "TEXT" },
  "HAB.FREQUENCY.YESTERDAY": { promptId: "HAB.I4.FREQUENCY.01", investigation: 4, sensitivity: "P2", type: "INTEGER" },
  "HAB.I4.OBSERVER.TEXT": { promptId: "HAB.I4.OBSERVER.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.I4.INSIGHT.TEXT": { promptId: "HAB.I4.INSIGHT.01", investigation: 4, sensitivity: "P2", type: "TEXT" },
  "HAB.EQUATION.TEXT": { promptId: "HAB.I5.EQUATION.01", investigation: 5, sensitivity: "P2", type: "TEXT" },
  "HAB.EQUATION.CONFIDENCE_PRE": { promptId: "HAB.I5.CONFIDENCE.01", investigation: 5, sensitivity: "P2", type: "INTEGER" },
  "HAB.FALSIFICATION.TEXT": { promptId: "HAB.I5.FALSIFICATION.01", investigation: 5, sensitivity: "P2", type: "TEXT" },
  "HAB.FALSIFICATION.MISUNDERSTOOD": { promptId: "HAB.I5.FALSIFICATION.02", investigation: 5, sensitivity: "P2", type: "TEXT" },
  "HAB.I5.OBSERVER.TEXT": { promptId: "HAB.I5.OBSERVER.01", investigation: 5, sensitivity: "P2", type: "TEXT" },
  "HAB.I5.INSIGHT.TEXT": { promptId: "HAB.I5.INSIGHT.01", investigation: 5, sensitivity: "P2", type: "TEXT" },
  "HAB.I6.INSIGHT.TEXT": { promptId: "HAB.I6.INSIGHT.01", investigation: 6, sensitivity: "P2", type: "TEXT" },
  "HAB.CONTROL.POST": { promptId: "HAB.I8.CONTROL.01", investigation: 8, sensitivity: "P2", type: "INTEGER" },
  "HAB.EQUATION.CONFIDENCE_POST": { promptId: "HAB.I8.CONFIDENCE.01", investigation: 8, sensitivity: "P2", type: "INTEGER" },
  "HAB.I8.CUE_FREQUENCY.TEXT": { promptId: "HAB.I8.REFLECTION.01", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.ROUTINE_USE.TEXT": { promptId: "HAB.I8.REFLECTION.02", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.HARDEST.TEXT": { promptId: "HAB.I8.REFLECTION.03", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.BEST.TEXT": { promptId: "HAB.I8.REFLECTION.04", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.DIFFICULTY_CHANGE.TEXT": { promptId: "HAB.I8.REFLECTION.05", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.EVIDENCE.SUPPORTING": { promptId: "HAB.I8.SUPPORTING.01", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.EVIDENCE.CHALLENGING": { promptId: "HAB.I8.CHALLENGING.01", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.ASSUMPTION.TEXT": { promptId: "HAB.I8.REFLECTION.08", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.META_HABIT.PLAN": { promptId: "HAB.I8.META_HABIT.01", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.I8.OBSERVER.TEXT": { promptId: "HAB.I8.OBSERVER.01", investigation: 8, sensitivity: "P2", type: "TEXT" },
  "HAB.AGENCY.REFLECTION": { promptId: "HAB.I9.AGENCY.01", investigation: 9, sensitivity: "P2", type: "TEXT" },
  "HAB.I9.CAPABILITY.TEXT": { promptId: "HAB.I9.CAPABILITY.01", investigation: 9, sensitivity: "P2", type: "TEXT" },
  "HAB.I9.FUTURE_LETTER": { promptId: "HAB.I9.LETTER.01", investigation: 9, sensitivity: "P3", type: "TEXT" },
  "HAB.NEXT_PATTERN.TEXT": { promptId: "HAB.I9.NEXT.01", investigation: 9, sensitivity: "P2", type: "TEXT" },
} as const;

export type CanonicalField = keyof typeof fieldRegistry;

export const investigations = [
  { number: 1, title: "The Hook", mission: "Meet someone whose habits changed everything.", time: "5 min", phase: "Investigation" },
  { number: 2, title: "The Pattern", mission: "Name one repeated pattern and find evidence that it exists.", time: "5 min", phase: "Investigation" },
  { number: 3, title: "The Revelation", mission: "Discover the hidden structure of a habit.", time: "5 min", phase: "Investigation" },
  { number: 4, title: "Habit Mapping", mission: "Map the structure of one real habit as carefully as you can.", time: "15 min", phase: "Investigation" },
  { number: 5, title: "Behaviour Equation", mission: "Write a working explanation that can be challenged.", time: "10 min", phase: "Investigation" },
  { number: 6, title: "Behaviour Contract", mission: "Design a seven-day test of your working equation.", time: "10 min", phase: "Investigation" },
  { number: 7, title: "7-Day Experiment", mission: "Notice the first target opportunity each day and record what happens.", time: "7 days", phase: "Experiment" },
  { number: 8, title: "Evidence Review", mission: "Review what supported and challenged your explanation.", time: "10 min", phase: "Review" },
  { number: 9, title: "Behaviour Profile", mission: "Bring your evidence, experiment and updated understanding together.", time: "10 min", phase: "Synthesis" },
] as const;

export const storyEpisodeOne = [
  "Meet Sipho.",
  "Sipho is fourteen. He lives with his grandmother in a small house near the taxi rank in Alexandra. His grandmother counts coins every morning—pension money, carefully rationed. Every Monday morning, she gives Sipho R20 for school. Not for sweets. For school.",
  "Every Monday, school ends at two. Sipho walks the same route home. The same taxi rank. The same corner. The same spaza shop on the right. The R20 sits in his pocket. And every Monday, without quite deciding to, he turns into the shop.",
  "His hand reaches for the sweets before he has properly thought about it. Same shelf. Same packet. Same movement.",
  "Sweet now. Gone before he gets home. Regret later. But the regret comes later. The sweetness comes first.",
  "‘I don’t know what I want to do,’ he says when people ask. ‘Something that makes money.’",
  "He doesn’t know what that means. He just knows his grandmother counts coins. He just knows he keeps buying sweets. He just knows the R20 disappears and he feels worse than before.",
  "One Sunday afternoon, his grandmother's chair breaks. A leg wobbles. He pushes a piece of folded cardboard into the loose joint. Functional. Clever. He does not think about it. He just does it.",
  "Someone notices. A neighbour. ‘You fixed that. My radio is broken. Can you look at it?’",
  "He doesn’t know how to fix a radio. But he tries.",
  "That evening, back home, he opens the radio. He looks at the wires. He does not know what he is doing. But he keeps looking. He keeps trying. Something clicks.",
  "He fixes it.",
  "‘I could charge for this,’ he thinks.",
  "Then he stops. He does not say this out loud. He has never said anything like that out loud.",
  "He is fourteen. He has no plan. He has no savings. He has no idea what he is becoming.",
  "But he just fixed a radio.",
  "And something shifted.",
];

export const storyEpisodeTwo = [
  "Sipho fixed the radio. He steadied his grandmother's chair.",
  "The sweets had repeated themselves every week. Now something else was beginning to repeat: broken thing, curiosity, try.",
  "He did not plan to become someone who fixes things. He just kept trying. He kept showing up. He kept persisting.",
  "But here is what nobody told him: the habit was not the problem. The loop was the problem.",
  "A useful way to understand a habit is as a loop: Cue → Routine → Reward.",
  "The brain learns to repeat a pattern because it produces some kind of payoff—even when that payoff comes with a cost.",
  "Sipho’s sweets habit:",
  "Cue: Monday afternoon. School ends. R20 in his pocket. Same route. Same shop. Boredom. Feeling invisible.",
  "Routine: Spend R20 on sweets.",
  "Reward: A few minutes of sweetness, feeling like someone who can choose.",
  "Sipho liked the sweets. But maybe it had never been only the sweets.",
  "There was that moment at the counter when the R20 was in his hand and the choice was his. For a few minutes, he could choose something simply because he wanted it.",
  "Fixing the radio had given him something strangely similar. Except stronger.",
  "He had looked at something that did not work, kept trying, and made it work.",
  "At the shop he could choose something.",
  "With the radio, he could make something happen.",
  "The sweets were part of the reward. But perhaps there was something underneath them too: for a moment, the choice was his.",
  "His fixing habit:",
  "Cue: Broken thing. Challenge. Curiosity.",
  "Routine: Try. Fail. Try again. Learn.",
  "Reward: The feeling of making something work. Of being noticed. Of being useful.",
  "Both habits gave him something. One cost him R20 and made him feel worse. The other built something and made him feel seen.",
  "Trying harder was not the whole answer. Sipho needed to understand the pattern he was repeating.",
  "Once he could see the loop, he had something he could experiment with.",
  "But he was fourteen. He did not know this yet.",
  "He just knew he felt something different when he fixed the radio.",
  "The next day, Monday, his grandmother gave him the week’s R20.",
  "School ended at two.",
  "Same route. Same shop. Same shelf.",
  "His hand reached toward the sweets before he had properly decided.",
  "He stopped.",
  "He still wanted them.",
  "That surprised him.",
  "His fingers tightened around the packet.",
  "For a second, putting it back felt harder than picking it up had felt.",
  "He put it back.",
  "On the shelf behind the counter was a packet of screws.",
  "He looked at them.",
  "The sweets would give him something for a few minutes. The screws might help him make something work.",
  "Both were choices.",
  "But they did not leave him in the same place.",
  "He bought the screws.",
  "Nothing dramatic happened.",
  "He did not suddenly become disciplined. He did not stop liking sweets. Tomorrow the shelf would still be there.",
  "He had chosen another routine once.",
  "Once was not a new habit.",
  "But once was evidence that another routine was possible.",
  "He put the screws in his pocket and walked home.",
  "He walked home, and he heard a voice. His grandmother was talking to the neighbour. ‘He fixed your radio? My Sipho?’",
  "She sounded surprised. She sounded proud.",
  "He kept walking. He did not stop. He felt the screws in his pocket.",
  "He did not know what he was building. He just knew he was building something.",
  "That evening, Myah walked past his house. She saw him sitting outside, holding the screws. She did not say anything. She just nodded. Like she understood.",
  "She walked on.",
  "Sipho stayed there, holding the screws, not knowing what came next.",
];

export const fieldLabels: Record<string, string> = {
  "HAB.CONTROL.PRE": "Habit control rating — before",
  "HAB.PATTERN.TARGET": "Habit investigated",
  "HAB.EVIDENCE.INITIAL": "Initial evidence",
  "HAB.CUE.TEXT": "Cue",
  "HAB.ROUTINE.TEXT": "Routine",
  "HAB.REWARD.OBVIOUS": "Obvious reward",
  "HAB.REWARD.LESS_OBVIOUS": "Less-obvious reward",
  "HAB.COST.TEXT": "Cost",
  "HAB.ENVIRONMENT.TEXT": "Environment",
  "HAB.ALTERNATIVE.TEXT": "Replacement routine",
  "HAB.EQUATION.TEXT": "Working equation",
  "HAB.FALSIFICATION.TEXT": "What could challenge it",
  "HAB.I2.OBSERVER.TEXT": "Observer question — reward sought",
  "HAB.I2.INSIGHT.TEXT": "Pattern insight",
  "HAB.FALSIFICATION.MISUNDERSTOOD": "Evidence that could show the pattern was misunderstood",
  "HAB.I4.OBSERVER.TEXT": "Observer question — visible weekly pattern",
  "HAB.I4.INSIGHT.TEXT": "Habit mapping insight",
  "HAB.I5.OBSERVER.TEXT": "Observer challenge to the equation",
  "HAB.I5.INSIGHT.TEXT": "Behaviour equation insight",
  "HAB.I6.INSIGHT.TEXT": "Behaviour contract insight",
  "HAB.CONTROL.POST": "Habit control rating — after",
  "HAB.I8.CUE_FREQUENCY.TEXT": "Cue frequency reflection",
  "HAB.I8.ROUTINE_USE.TEXT": "Replacement routine reflection",
  "HAB.I8.HARDEST.TEXT": "Hardest part of the experiment",
  "HAB.I8.BEST.TEXT": "Best part of the experiment",
  "HAB.I8.DIFFICULTY_CHANGE.TEXT": "How the habit changed across the week",
  "HAB.EVIDENCE.SUPPORTING": "Supported the equation",
  "HAB.EVIDENCE.CHALLENGING": "Challenged the equation",
  "HAB.I8.ASSUMPTION.TEXT": "Assumption that became harder to defend",
  "HAB.META_HABIT.PLAN": "Plan to keep the meta-habit alive",
  "HAB.I8.OBSERVER.TEXT": "Observer conclusion",
  "HAB.AGENCY.REFLECTION": "Agency reflection",
  "HAB.I9.CAPABILITY.TEXT": "One sentence describing what I can now do",
  "HAB.I9.FUTURE_LETTER": "Letter to my future self",
  "HAB.NEXT_PATTERN.TEXT": "Next habit to investigate",
};
