"use client";
import { readClientResponse, clientResponseMessage, clientResponseDenied } from "@/lib/client-response";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { WorkspaceMenu } from "@/components/workspace-menu";
import { LayoutDashboard, Users, ClipboardCheck, BookOpen, Settings2 } from "lucide-react";
import styles from "./commercial.module.css";

type Identity = { email: string; displayName: string };
type Organisation = { id: string; name: string; organisation_type: string; website: string | null; research_status: string; status: string; notes: string | null };
type Contact = { id: string; organisation_id: string; full_name: string | null; job_title: string | null; email: string | null; phone: string | null; linkedin_url: string | null; buying_role: string | null; verification_status: string; is_primary: boolean };
type Opportunity = { id: string; code: string; organisation_id: string; opportunity_name: string; lane: "SCHOOL" | "EMERGING_ADULT" | "WORKPLACE"; edition: string; buyer_group: string; opportunity_type: string; priority: string; stage: string; strategic_question: string | null; commercial_thesis: string | null; recommended_tier: string | null; pathway: string | null; proposal_code: string | null; proposal_status: string; contact_status: string; owner_email: string | null; wave: string; next_action: string | null; next_action_due: string | null; hold_reason: string | null; last_activity_at: string | null };
type Proposal = { id: string; proposal_code: string; opportunity_id: string; title: string; status: string; edition: string; version: string; frozen_at: string | null; sent_at: string | null; document_url: string | null };
type Task = { id: string; opportunity_id: string | null; title: string; status: string; priority: string; due_at: string | null; owner_email: string | null };
type Activity = { id: string; opportunity_id: string; activity_type: string; direction: string; subject: string | null; body: string | null; occurred_at: string; actor_email: string };
type Snapshot = { identity: Identity; roles: string[]; canWrite: boolean; canAdmin: boolean; metrics: { organisations: number; opportunities: number; school: number; emergingAdult: number; workplace: number; waveOne: number; frozenProposals: number; discovery: number; won: number; openTasks: number }; organisations: Organisation[]; contacts: Contact[]; opportunities: Opportunity[]; proposals: Proposal[]; tasks: Task[]; activities: Activity[]; controlledStages: string[] };

const stageOrder = ["RESEARCH","QUALIFY","QUALIFIED","THESIS_READY","PROPOSAL_DRAFT","PROPOSAL_FROZEN","CONTACTED","DISCOVERY","SCOPED","PROPOSAL_SENT","NEGOTIATION","WON","NURTURE","WATCHLIST","HOLD","LOST"];
const laneNames: Record<string, string> = { SCHOOL: "School", EMERGING_ADULT: "Emerging Adult", WORKPLACE: "Workplace" };
const laneQuestion: Record<string, string> = { SCHOOL: "What happens after learning?", EMERGING_ADULT: "What happens when capability meets independence and real work?", WORKPLACE: "What happens when development meets the next real situation?" };

function pretty(value: string) { return value.toLowerCase().split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function shortDate(value: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("en-ZA", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }
async function api(action?: Record<string, unknown>) { const response = await fetch("/api/commercial", { method: action ? "POST" : "GET", headers: action ? { "Content-Type": "application/json" } : undefined, body: action ? JSON.stringify(action) : undefined, cache: "no-store" }); return readClientResponse<Snapshot>(response, action ? "The commercial update could not be saved. Try again." : "The commercial workspace could not open. Try again.", action ? undefined : value => ["organisations","contacts","opportunities","proposals","tasks","activities","controlledStages"].every(field => Array.isArray(value[field])) && Boolean(value.metrics)); }

export function CommercialWorkspace({ identity, roles }: { identity: Identity; roles: string[] }) {
  const [data, setData] = useState<Snapshot | null>(null);
  const router = useRouter(), params = useSearchParams();
  type View = "overview" | "pipeline" | "accounts" | "tasks" | "proposals";
  const requested = params.get("section");
  const view: View = ["overview","pipeline","accounts","tasks","proposals"].includes(requested ?? "") ? requested as View : "overview";
  function setView(next: View) {router.push(`/commercial?section=${next}`, {scroll:false});}
  const [lane, setLane] = useState<"ALL" | Opportunity["lane"]>("ALL");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showNewOpportunity, setShowNewOpportunity] = useState(false);
  const [showNewOrganisation, setShowNewOrganisation] = useState(false);

  async function refresh() { setLoading(true); try { const next = (await api()) as Snapshot; setData(next); setError(null); } catch (err) { if (clientResponseDenied(err)) setData(null); setError(clientResponseMessage(err, "The commercial workspace could not open. Try again.")); } finally { setLoading(false); } }
  useEffect(() => {
    let cancelled=false;
    void api().then(next=>{if(!cancelled){setData(next as Snapshot);setError(null);}}).catch(err=>{if(!cancelled){if(clientResponseDenied(err))setData(null);setError(clientResponseMessage(err, "The commercial workspace could not open. Try again."));}}).finally(()=>{if(!cancelled)setLoading(false);});
    return ()=>{cancelled=true;};
  }, []);
  const selected = data?.opportunities.find((item) => item.id === selectedId) ?? null;
  const filtered = useMemo(() => data?.opportunities.filter((item) => lane === "ALL" || item.lane === lane) ?? [], [data, lane]);
  async function mutate(payload: Record<string, unknown>) { setBusy(true); try { await api(payload); await refresh(); return true; } catch (err) { if (clientResponseDenied(err)) setData(null); setError(clientResponseMessage(err, "The commercial update could not be saved. Try again.")); return false; } finally { setBusy(false); } }

  return <div className={styles.shell}>
    <main className={styles.main}>
      <header className={styles.topbar}><div><span className={styles.eyebrow}>BIS · Commercial workspace</span><h1>{view === "overview" ? "Partnerships, pipeline and execution." : pretty(view)}</h1></div><div className={styles.topActions}><button className={styles.secondary} onClick={() => void refresh()} disabled={loading}>Refresh</button><button className={styles.primary} onClick={() => setShowNewOpportunity(true)} disabled={!data?.canWrite}>+ New opportunity</button></div></header>
      {error && <div className={styles.error}>{error}</div>}
      {loading && !data ? <div className={styles.loading}>Loading BIS Commercial Workspace…</div> : null}
      {data && view === "overview" && <Overview data={data} setView={setView} setLane={setLane} select={(id) => { setSelectedId(id); setView("pipeline"); }} />}
      {data && view === "pipeline" && <Pipeline opportunities={filtered} organisations={data.organisations} lane={lane} setLane={setLane} select={setSelectedId} />}
      {data && view === "accounts" && <Accounts data={data} onAdd={() => setShowNewOrganisation(true)} select={(id) => { setSelectedId(id); setView("pipeline"); }} />}
      {data && view === "tasks" && <Tasks data={data} busy={busy} mutate={mutate} />}
      {data && view === "proposals" && <Proposals data={data} />}
      {selected && data && <OpportunityPanel error={error} key={selected.id} opportunity={selected} organisation={data.organisations.find((item) => item.id === selected.organisation_id)} contacts={data.contacts.filter((item) => item.organisation_id === selected.organisation_id)} activities={data.activities.filter((item) => item.opportunity_id === selected.id)} stages={data.controlledStages} canWrite={data.canWrite} busy={busy} close={() => setSelectedId(null)} mutate={mutate} />}
      {showNewOpportunity && data && <NewOpportunityModal error={error} organisations={data.organisations} busy={busy} close={() => setShowNewOpportunity(false)} mutate={async (payload) => { const saved=await mutate(payload); if(saved)setShowNewOpportunity(false); return saved; }} />}
      {showNewOrganisation && data && <NewOrganisationModal error={error} busy={busy} close={() => setShowNewOrganisation(false)} mutate={async (payload) => { const saved=await mutate(payload); if(saved)setShowNewOrganisation(false); return saved; }} />}
    </main>
    <WorkspaceMenu label="Commercial workspace menu" groups={[
      {label:"Commercial operations",items:[
        {id:"overview",label:"Overview",detail:"Partnership priorities",href:"/commercial?section=overview",icon:LayoutDashboard,active:view==="overview"},
        {id:"pipeline",label:"Pipeline",detail:"Opportunities and next actions",href:"/commercial?section=pipeline",icon:Settings2,active:view==="pipeline"},
        {id:"accounts",label:"Organisations",detail:"Accounts and contacts",href:"/commercial?section=accounts",icon:Users,active:view==="accounts"},
        {id:"tasks",label:"Tasks",detail:"Follow-up and execution",href:"/commercial?section=tasks",icon:ClipboardCheck,active:view==="tasks"},
        {id:"proposals",label:"Proposals",detail:"Prepared and frozen proposals",href:"/commercial?section=proposals",icon:BookOpen,active:view==="proposals"},
      ]},
      {label:identity.displayName,items:[...(roles.includes("SYSTEM_ADMIN")?[{id:"staff",label:"Staff workspace",detail:"Programme operations",href:"/workspace?view=admin",icon:LayoutDashboard}]:[]),{id:"profile",label:"Profile",detail:"Account and sign out",href:"/profile",icon:Users}]},
    ]}/>
  </div>;
}

function Overview({ data, setView, setLane, select }: { data: Snapshot; setView: (view: "overview" | "pipeline" | "accounts" | "tasks" | "proposals") => void; setLane: (lane: "ALL" | Opportunity["lane"]) => void; select: (id: string) => void }) {
  const waveOne = data.opportunities.filter((item) => item.wave === "WAVE_1");
  const overdue = data.tasks.filter((task) => task.status !== "DONE" && task.due_at && new Date(task.due_at) < new Date());
  return <div className={styles.stack}>
    <section className={styles.metrics}><Metric label="Opportunities" value={data.metrics.opportunities} note={`${data.metrics.organisations} parent accounts`} /><Metric label="Wave 1" value={data.metrics.waveOne} note="Controlled execution queue" /><Metric label="Frozen masters" value={data.metrics.frozenProposals} note="Customer-facing proposal masters" /><Metric label="Open tasks" value={data.metrics.openTasks} note={`${overdue.length} overdue`} /></section>
    <section className={styles.laneGrid}>{(["SCHOOL","EMERGING_ADULT","WORKPLACE"] as const).map((item) => { const count = data.opportunities.filter((o) => o.lane === item).length; const wave = waveOne.filter((o) => o.lane === item).length; return <button className={styles.laneCard} key={item} onClick={() => { setLane(item); setView("pipeline"); }}><span className={styles.eyebrow}>{laneNames[item]}</span><strong>{count}</strong><p>{laneQuestion[item]}</p><small>{wave} Wave-1 opportunities →</small></button>; })}</section>
    <section className={styles.gridTwo}><div className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Execution frontier</span><h2>Wave 1</h2></div><button className={styles.textButton} onClick={() => setView("pipeline")}>Open pipeline →</button></div><div className={styles.list}>{waveOne.map((item) => <button className={styles.rowButton} key={item.id} onClick={() => select(item.id)}><div><strong>{item.opportunity_name}</strong><span>{laneNames[item.lane]} · {pretty(item.stage)}</span></div><div className={styles.rowRight}><span>{item.next_action ?? "Set next action"}</span><small>{shortDate(item.next_action_due)}</small></div></button>)}</div></div>
      <div className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Stage discipline</span><h2>What is actually moving?</h2></div></div><div className={styles.stageSummary}>{stageOrder.map((stage) => ({ stage, count: data.opportunities.filter((item) => item.stage === stage).length })).filter((item) => item.count > 0).map((item) => <div key={item.stage}><span>{pretty(item.stage)}</span><strong>{item.count}</strong></div>)}</div></div></section>
  </div>;
}
function Metric({ label, value, note }: { label: string; value: number; note: string }) { return <div className={styles.metric}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }

function Pipeline({ opportunities, organisations, lane, setLane, select }: { opportunities: Opportunity[]; organisations: Organisation[]; lane: "ALL" | Opportunity["lane"]; setLane: (lane: "ALL" | Opportunity["lane"]) => void; select: (id: string) => void }) {
  const activeStages = stageOrder.filter((stage) => opportunities.some((item) => item.stage === stage));
  return <section><div className={styles.filters}>{(["ALL","SCHOOL","EMERGING_ADULT","WORKPLACE"] as const).map((item) => <button className={lane === item ? styles.filterActive : ""} key={item} onClick={() => setLane(item)}>{item === "ALL" ? "All lanes" : laneNames[item]}</button>)}</div><div className={styles.board}>{activeStages.map((stage) => { const items = opportunities.filter((item) => item.stage === stage); return <div className={styles.column} key={stage}><div className={styles.columnHead}><span>{pretty(stage)}</span><strong>{items.length}</strong></div><div className={styles.columnBody}>{items.map((item) => { const org = organisations.find((o) => o.id === item.organisation_id); return <button className={styles.oppCard} key={item.id} onClick={() => select(item.id)}><div className={styles.cardMeta}><span className={`${styles.lanePill} ${styles[item.lane.toLowerCase()]}`}>{laneNames[item.lane]}</span><span>{item.priority}</span></div><strong>{item.opportunity_name}</strong><small>{org?.name ?? "Organisation"}</small>{item.commercial_thesis && <p>{item.commercial_thesis}</p>}<div className={styles.nextAction}><span>Next</span><b>{item.next_action ?? "Not set"}</b><small>{shortDate(item.next_action_due)}</small></div></button>; })}</div></div>; })}</div></section>;
}

function Accounts({ data, onAdd, select }: { data: Snapshot; onAdd: () => void; select: (id: string) => void }) {
  return <section className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Parent accounts</span><h2>{data.organisations.length} organisations</h2></div><button className={styles.primarySmall} onClick={onAdd} disabled={!data.canWrite}>+ Organisation</button></div><div className={styles.accountTable}><div className={styles.tableHead}><span>Organisation</span><span>Type</span><span>Opportunities</span><span>Buyer verification</span></div>{data.organisations.map((organisation) => { const opportunities = data.opportunities.filter((item) => item.organisation_id === organisation.id); const contacts = data.contacts.filter((item) => item.organisation_id === organisation.id); return <div className={styles.tableRow} key={organisation.id}><div><strong>{organisation.name}</strong><small>{organisation.status}</small></div><span>{organisation.organisation_type}</span><div className={styles.inlineLinks}>{opportunities.map((opportunity) => <button key={opportunity.id} onClick={() => select(opportunity.id)}>{opportunity.code}</button>)}</div><span>{contacts.some((contact) => contact.verification_status === "VERIFIED") ? "Verified" : "Needs verification"}</span></div>; })}</div></section>;
}

function Tasks({ data, busy, mutate }: { data: Snapshot; busy: boolean; mutate: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const open = data.tasks.filter((task) => task.status !== "DONE"); const done = data.tasks.filter((task) => task.status === "DONE");
  return <section className={styles.gridTwo}><div className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Action queue</span><h2>Open tasks</h2></div><span className={styles.count}>{open.length}</span></div><div className={styles.list}>{open.map((task) => { const opportunity = data.opportunities.find((item) => item.id === task.opportunity_id); return <div className={styles.taskRow} key={task.id}><div><strong>{task.title}</strong><span>{opportunity?.opportunity_name ?? "General"} · {task.priority}</span><small>Due {shortDate(task.due_at)}</small></div><button disabled={busy || !data.canWrite} onClick={() => void mutate({ action: "completeTask", id: task.id })}>Complete</button></div>; })}</div></div><div className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Completed</span><h2>Recent completions</h2></div></div><div className={styles.list}>{done.slice(0,20).map((task) => <div className={styles.doneRow} key={task.id}><span>✓</span><div><strong>{task.title}</strong><small>{task.owner_email}</small></div></div>)}{done.length === 0 && <p className={styles.empty}>Completed actions will appear here.</p>}</div></div></section>;
}

function Proposals({ data }: { data: Snapshot }) { return <section className={styles.card}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Controlled documents</span><h2>Proposal registry</h2></div><span className={styles.count}>{data.proposals.length}</span></div><div className={styles.proposalGrid}>{data.proposals.map((proposal) => { const opportunity = data.opportunities.find((item) => item.id === proposal.opportunity_id); return <article key={proposal.id} className={styles.proposalCard}><div><span className={styles.statusPill}>{proposal.status}</span><span>v{proposal.version}</span></div><h3>{proposal.title}</h3><p>{proposal.proposal_code}</p><small>{opportunity?.edition} · Frozen {shortDate(proposal.frozen_at)}</small><div className={styles.proposalFoot}><span>{proposal.sent_at ? `Sent ${shortDate(proposal.sent_at)}` : "Not sent"}</span>{proposal.document_url && <a href={proposal.document_url}>Open document</a>}</div></article>; })}</div></section>; }

function OpportunityPanel({ error, opportunity, organisation, contacts, activities, stages, canWrite, busy, close, mutate }: { error:string|null; opportunity: Opportunity; organisation?: Organisation; contacts: Contact[]; activities: Activity[]; stages: string[]; canWrite: boolean; busy: boolean; close: () => void; mutate: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const [stage, setStage] = useState(opportunity.stage); const [nextAction, setNextAction] = useState(opportunity.next_action ?? ""); const [nextActionDue, setNextActionDue] = useState(opportunity.next_action_due ?? ""); const [activityType, setActivityType] = useState("NOTE"); const [activityBody, setActivityBody] = useState(""); const [contactName, setContactName] = useState(""); const [contactTitle, setContactTitle] = useState(""); const [contactEmail, setContactEmail] = useState("");
  return <CommercialDialog title={opportunity.opportunity_name} close={close} drawer><div className={styles.drawer}><div className={styles.drawerHead}><div><span className={styles.eyebrow}>{opportunity.code} · {laneNames[opportunity.lane]}</span><h2>{opportunity.opportunity_name}</h2><p>{organisation?.name}</p></div><button className={styles.close} aria-label="Close opportunity" onClick={close}>×</button></div><div className={styles.detailGrid}><div><span>Edition</span><strong>{opportunity.edition}</strong></div><div><span>Buyer</span><strong>{opportunity.buyer_group}</strong></div><div><span>Tier</span><strong>{opportunity.recommended_tier ?? "To scope"}</strong></div><div><span>Proposal</span><strong>{opportunity.proposal_code ?? "Not started"}</strong></div></div>{opportunity.commercial_thesis && <div className={styles.thesis}><span className={styles.eyebrow}>Commercial thesis</span><p>{opportunity.commercial_thesis}</p></div>}{opportunity.pathway && <div className={styles.pathway}><span>Pathway</span><strong>{opportunity.pathway}</strong></div>}{opportunity.hold_reason && <div className={styles.hold}>{opportunity.hold_reason}</div>}
    {error && <p role="alert" className={styles.error}>{error}</p>}
    <section className={styles.drawerSection}><h3>Control the opportunity</h3><div className={styles.formGrid}><label>Stage<select value={stage} onChange={(event) => setStage(event.target.value)} disabled={!canWrite}>{stages.map((item) => <option key={item} value={item}>{pretty(item)}</option>)}</select></label><label>Next action<input value={nextAction} onChange={(event) => setNextAction(event.target.value)} disabled={!canWrite}/></label><label>Due<input type="date" value={nextActionDue} onChange={(event) => setNextActionDue(event.target.value)} disabled={!canWrite}/></label></div><button className={styles.primarySmall} disabled={!canWrite || busy} onClick={() => void mutate({ action: "updateOpportunity", id: opportunity.id, stage, nextAction, nextActionDue: nextActionDue || null })}>Save opportunity</button></section>
    <section className={styles.drawerSection}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Buyer map</span><h3>Contacts</h3></div><span className={styles.count}>{contacts.length}</span></div>{contacts.map((contact) => <div className={styles.contact} key={contact.id}><div><strong>{contact.full_name ?? "Unnamed contact"}</strong><span>{contact.job_title ?? contact.buying_role}</span></div><div><small>{contact.email ?? "No email"}</small><small>{contact.verification_status}</small></div></div>)}{canWrite && <form className={styles.inlineForm} onSubmit={(event) => { event.preventDefault(); void mutate({ action: "createContact", organisationId: opportunity.organisation_id, fullName: contactName, jobTitle: contactTitle, email: contactEmail, buyingRole: opportunity.buyer_group }).then(saved => { if(!saved)return; setContactName(""); setContactTitle(""); setContactEmail(""); }); }}><input aria-label="Contact name" placeholder="Contact name" value={contactName} onChange={(e) => setContactName(e.target.value)}/><input aria-label="Contact title" placeholder="Title / role" value={contactTitle} onChange={(e) => setContactTitle(e.target.value)}/><input aria-label="Contact email" type="email" placeholder="Email (verify first)" value={contactEmail} onChange={(e) => setContactEmail(e.target.value)}/><button disabled={busy}>Add contact</button></form>}</section>
    <section className={styles.drawerSection}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>Timeline</span><h3>Activities</h3></div></div>{canWrite && <form className={styles.activityForm} onSubmit={(event) => { event.preventDefault(); if (!activityBody.trim()) return; void mutate({ action: "addActivity", opportunityId: opportunity.id, activityType, body: activityBody, direction: activityType === "NOTE" ? "INTERNAL" : "OUTBOUND" }).then(saved => {if(saved)setActivityBody("");}); }}><select aria-label="Activity type" value={activityType} onChange={(event) => setActivityType(event.target.value)}><option value="NOTE">Internal note</option><option value="EMAIL">Email</option><option value="WHATSAPP">WhatsApp</option><option value="CALL">Call</option><option value="LINKEDIN">LinkedIn</option><option value="MEETING">Meeting</option></select><textarea aria-label="Activity details" placeholder="What happened?" value={activityBody} onChange={(event) => setActivityBody(event.target.value)}/><button disabled={busy}>Log activity</button></form>}<div className={styles.timeline}>{activities.map((activity) => <div className={styles.timelineItem} key={activity.id}><span className={styles.timelineDot}/><div><strong>{activity.activity_type}</strong><p>{activity.body ?? activity.subject ?? "Activity logged"}</p><small>{shortDate(activity.occurred_at)} · {activity.actor_email}</small></div></div>)}{activities.length === 0 && <p className={styles.empty}>No activity has been logged yet.</p>}</div></section>
    </div></CommercialDialog>;
}

function NewOpportunityModal({ error, organisations, busy, close, mutate }: { error:string|null; organisations: Organisation[]; busy: boolean; close: () => void; mutate: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const [organisationId, setOrganisationId] = useState(organisations[0]?.id ?? ""); const [name, setName] = useState(""); const [lane, setLane] = useState<Opportunity["lane"]>("SCHOOL"); const edition = lane === "SCHOOL" ? "School 14–18" : lane === "EMERGING_ADULT" ? "Emerging Adult 18–25" : "Workplace 25+";
  return <Modal error={error} title="Create opportunity" eyebrow="New commercial record" close={close}><form className={styles.modalForm} onSubmit={(event) => { event.preventDefault(); void mutate({ action: "createOpportunity", organisationId, opportunityName: name, lane, edition, buyerGroup: lane === "WORKPLACE" ? "People & Culture / L&D" : lane === "EMERGING_ADULT" ? "Programme / Graduate Development" : "CSI / Education" }); }}><label>Organisation<select value={organisationId} onChange={(event) => setOrganisationId(event.target.value)}>{organisations.map((org) => <option key={org.id} value={org.id}>{org.name}</option>)}</select></label><label>Opportunity name<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Graduate Programme"/></label><label>Commercial lane<select value={lane} onChange={(event) => setLane(event.target.value as Opportunity["lane"])}><option value="SCHOOL">School</option><option value="EMERGING_ADULT">Emerging Adult</option><option value="WORKPLACE">Workplace</option></select></label><div className={styles.modalActions}><button type="button" className={styles.secondary} onClick={close}>Cancel</button><button className={styles.primary} disabled={busy}>Create opportunity</button></div></form></Modal>;
}
function NewOrganisationModal({ error, busy, close, mutate }: { error:string|null; busy: boolean; close: () => void; mutate: (payload: Record<string, unknown>) => Promise<boolean> }) { const [name, setName] = useState(""); const [type, setType] = useState(""); return <Modal error={error} title="Add organisation" eyebrow="Parent account" close={close}><form className={styles.modalForm} onSubmit={(event: FormEvent) => { event.preventDefault(); void mutate({ action: "createOrganisation", name, organisationType: type }); }}><label>Organisation name<input required value={name} onChange={(event) => setName(event.target.value)}/></label><label>Organisation type<input required value={type} onChange={(event) => setType(event.target.value)} placeholder="Corporate, Foundation, NGO, School network…"/></label><div className={styles.modalActions}><button type="button" className={styles.secondary} onClick={close}>Cancel</button><button className={styles.primary} disabled={busy}>Add organisation</button></div></form></Modal>; }
function CommercialDialog({title,close,drawer=false,children}:{title:string;close:()=>void;drawer?:boolean;children:React.ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;if(!dialog)return;const overflow=document.body.style.overflow;const opener=document.activeElement as HTMLElement|null;document.body.style.overflow="hidden";dialog.showModal();return ()=>{dialog.close();document.body.style.overflow=overflow;opener?.focus();};},[]);
  return <dialog ref={ref} aria-label={title} className={drawer?styles.drawerDialog:styles.modalDialog} onCancel={close}>{children}</dialog>;
}
function Modal({ eyebrow, title, error, children, close }: { eyebrow: string; title: string; error:string|null; children: React.ReactNode; close: () => void }) { return <CommercialDialog title={title} close={close}><section className={styles.modal}><button className={styles.close} aria-label="Close form" onClick={close}>×</button><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2>{error && <p role="alert" className={styles.error}>{error}</p>}{children}</section></CommercialDialog>; }
