-- Read-only full platform inventory, including managed schemas.
-- Compare BIS-owned definitions separately from provider-managed version changes.
-- Never selects learner-authored data, auth.users, storage.objects or secret values.
select jsonb_build_object(
 'schemas', (select jsonb_agg(nspname order by nspname) from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema'),
 'relations', (select jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname,'kind',c.relkind,'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'options',c.reloptions,'definition',md5(case when c.relkind in ('v','m') then pg_get_viewdef(c.oid,true) else coalesce((select string_agg(a.attname||':'||format_type(a.atttypid,a.atttypmod)||':'||a.attnotnull||':'||coalesce(pg_get_expr(d.adbin,d.adrelid),''),'|' order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),'') end),'acl',c.relacl::text) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname not like 'pg_%' and n.nspname <> 'information_schema' and c.relkind in ('r','v','m','p')),
 'functions', (select jsonb_agg(jsonb_build_object('name',n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')','definition',md5(pg_get_functiondef(p.oid)),'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname not like 'pg_%' and n.nspname <> 'information_schema' and p.prokind='f'),
 'policies', (select jsonb_agg(jsonb_build_object('name',schemaname||'.'||tablename||'.'||policyname,'roles',roles,'cmd',cmd,'permissive',permissive,'using',qual,'check',with_check) order by schemaname,tablename,policyname) from pg_policies where schemaname not like 'pg_%' and schemaname <> 'information_schema'),
 'triggers', (select jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname||'.'||t.tgname,'definition',pg_get_triggerdef(t.oid),'enabled',t.tgenabled) order by n.nspname,c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
 'constraints', (select jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname||'.'||con.conname,'definition',pg_get_constraintdef(con.oid),'validated',con.convalidated) order by n.nspname,c.relname,con.conname) from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname not like 'pg_%' and n.nspname <> 'information_schema'),
 'indexes', (select jsonb_agg(jsonb_build_object('name',schemaname||'.'||indexname,'definition',indexdef) order by schemaname,indexname) from pg_indexes where schemaname not like 'pg_%' and schemaname <> 'information_schema'),
 'extensions', (select jsonb_agg(jsonb_build_object('name',extname,'version',extversion) order by extname) from pg_extension),
 'buckets', (select jsonb_agg(jsonb_build_object('name',id,'public',public,'fileSizeLimit',file_size_limit,'allowedMimeTypes',allowed_mime_types) order by id) from storage.buckets),
 'roleSettings', (select jsonb_agg(jsonb_build_object('role',r.rolname,'config',s.setconfig) order by r.rolname) from pg_db_role_setting s join pg_roles r on r.oid=s.setrole),
 'schemaGrants', (select jsonb_agg(jsonb_build_object('name',nspname,'acl',nspacl::text) order by nspname) from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema')
) as configuration;
