"use client";
import {useEffect,useRef,useState} from "react";
import {useEvidenceData,EvidenceState} from "../evidence-engine-client";
import {CalculationHistory} from "./calculation-history";
import {AssessmentHistory} from "../facilitator-assessment";
import {evidenceTitle,evidenceWording,type EvidenceRecord,type AssessmentWorkspace} from "@/lib/evidence-engine";
import {BIS_MODULES} from "@/lib/bis-catalogue";
type Timeline={records:EvidenceRecord[];index:{years:number[];labs:string[];record_count:number}};
const classes=["BASELINE","CONTEXT","PREDICTION","PLAN","OBSERVATION","OUTCOME","INTERPRETATION","TRANSFER","LEARNING_CHECK","SUPPORT_SIGNAL","UNCLASSIFIED"];
function date(value:string){return new Date(value).toLocaleDateString("en-ZA",{timeZone:"Africa/Johannesburg"});}
export function PortfolioWorkspace() {
 const [showCalculations,setShowCalculations]=useState(false);
 const [year,setYear]=useState(""),[lab,setLab]=useState(""),[evidenceClass,setClass]=useState(""),[older,setOlder]=useState<{query:string;records:EvidenceRecord[];hasMore:boolean}>({query:"",records:[],hasMore:true}),[paging,setPaging]=useState(false),[pageError,setPageError]=useState(""),[selected,setSelected]=useState<string[]>([]),[group,setGroup]=useState(""),[title,setTitle]=useState(""),[checked,setChecked]=useState(false),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const query=`view=timeline${year?`&year=${year}`:""}${lab?`&lab=${encodeURIComponent(lab)}`:""}${evidenceClass?`&class=${evidenceClass}`:""}`;
 const currentQuery=useRef(query);useEffect(()=>{currentQuery.current=query;},[query]);
 const timeline=useEvidenceData<Timeline>(query),sharing=useEvidenceData<AssessmentWorkspace>("view=workspace");
 const extra=older.query===query?older.records:[],records=[...(timeline.data?.records??[]),...extra],hasMore=older.query===query?older.hasMore:(timeline.data?.records.length??0)===60;
 const selectedRecords=records.filter(r=>selected.includes(r.id)&&r.status==="ACTIVE"&&["P0","P1","P2"].includes(r.sensitivity));
 const groups=sharing.data?.groups.filter(g=>selectedRecords.length>0&&selectedRecords.every(r=>r.lab_code===g.lab_code&&r.lab_version===g.lab_version))??[],activeGroup=groups.find(g=>g.id===group)?.id??groups[0]?.id??"";
 function resetSelection(){setSelected([]);setChecked(false);setRequestKey(crypto.randomUUID());setPageError("");}
 async function olderRecords(){
  const last=records.at(-1);if(!last||paging)return;setPaging(true);setPageError("");const started=query;
  try {const response=await fetch(`/api/evidence-engine?${query}&before=${encodeURIComponent(last.occurred_at)}&beforeId=${encodeURIComponent(last.id)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Older evidence could not be loaded.");if(currentQuery.current===started)setOlder({query:started,records:[...extra,...payload.records],hasMore:payload.records.length===60});}
  catch(cause){if(currentQuery.current===started)setPageError(cause instanceof Error?cause.message:"Older evidence could not be loaded.");}
  finally{setPaging(false);}
 }
 async function share(){if(await sharing.act({action:"share",cohortId:activeGroup,evidenceIds:selectedRecords.map(r=>r.id),title,requestKey})){resetSelection();setTitle("");}}
 return <main className="evidence-workspace"><p className="eyebrow">Your longitudinal record</p><h1>Evidence Portfolio</h1><p>Look back at what you recorded, questioned, attempted and learned. Original responses, later revisions and facilitator reviews retain their dates and sources. Only the records you choose to share become available for a group review.</p><div className="evidence-actions"><a className="evidence-button" href="/api/evidence-engine?view=learnerReport">Download my evidence report</a><button className="secondary" type="button" disabled={timeline.loading||sharing.loading} onClick={()=>{setOlder({query:"",records:[],hasMore:true});resetSelection();void timeline.load();void sharing.load();}}>Refresh portfolio</button></div>
 <div className="evidence-filters"><label>Year<select value={year} onChange={e=>{setYear(e.target.value);resetSelection();}}><option value="">All recorded years</option>{timeline.data?.index.years.slice().sort((a,b)=>b-a).map(y=><option value={y} key={y}>{y}</option>)}</select></label><label>Lab<select value={lab} onChange={e=>{setLab(e.target.value);resetSelection();}}><option value="">All Labs</option>{timeline.data?.index.labs.map(code=><option key={code} value={code}>{BIS_MODULES.find(m=>m.code===code)?.title??code}</option>)}</select></label><label>Evidence purpose<select value={evidenceClass} onChange={e=>{setClass(e.target.value);resetSelection();}}><option value="">All purposes</option>{classes.map(c=><option key={c} value={c}>{c==="UNCLASSIFIED"?"Awaiting source classification":c.toLowerCase().replaceAll("_"," ")}</option>)}</select></label></div><EvidenceState {...timeline} retry={()=>void timeline.load()}/>
 {timeline.data?<><p className="evidence-meta">{timeline.data.index.record_count} recorded evidence anchors in your history. {records.length} shown with the selected filters.</p>{!records.length?<section className="evidence-empty"><h2>{timeline.data.index.record_count?"No records match these filters":"Your record starts with your first response"}</h2><p>As you work through handbooks and Labs, your saved evidence appears here. The portfolio shows the history you have recorded.</p></section>:<ol className="evidence-timeline">{records.map(record=>{
 const eligible=record.status==="ACTIVE"&&["P0","P1","P2"].includes(record.sensitivity),label=evidenceTitle(record);
 return <li key={record.id} className="evidence-entry"><div className="evidence-entry-header">{eligible?<label><input aria-label={`Select evidence: ${label}`} type="checkbox" checked={selected.includes(record.id)} disabled={sharing.saving||(selected.length>=50&&!selected.includes(record.id))} onChange={e=>{setSelected(e.target.checked?[...selected,record.id]:selected.filter(id=>id!==record.id));setChecked(false);setRequestKey(crypto.randomUUID());}}/><span>{label}</span></label>:<h3>{label}</h3>}<time dateTime={record.occurred_at}>{date(record.occurred_at)}</time></div><p className="evidence-meta">{BIS_MODULES.find(m=>m.code===record.lab_code)?.title??record.lab_code} · {record.provenance==="LR"?"Handbook response":"Lab evidence"} · {record.evidence_class&&record.evidence_class!=="UNCLASSIFIED"?record.evidence_class.toLowerCase().replaceAll("_"," "):"Awaiting source classification"}</p><p className="evidence-wording">{record.status==="WITHDRAWN"?"Response passed or withdrawn":evidenceWording(record.value)}</p>{record.status!=="ACTIVE"?<p className="evidence-status">{record.status==="SUPERSEDED"?"Earlier response · retained after revision":"Withdrawn record"}</p>:null}{record.sensitivity==="P3"?<p className="evidence-meta">Highly personal reflection · available only to you in this portfolio.</p>:null}{record.supersedes_response_id?<p className="evidence-meta">Revises an earlier response. Both records remain in your history.</p>:null}<details><summary>Curriculum context and source</summary><p>{record.portfolio_purpose??"Preserved as original evidence; meaning has not yet been classified."}</p>{record.outcome?<p>Outcome: {record.outcome}</p>:null}{record.competency?<p>Competency: {record.competency}</p>:null}<p className="evidence-meta">{record.investigation_id} · {record.lab_version} · Recorded {date(record.recorded_at)} · {record.source_object_type.toLowerCase()}</p></details></li>;
 })}</ol>}{pageError?<p role="alert">{pageError}</p>:null}{hasMore&&records.length?<button type="button" className="secondary evidence-pager" disabled={paging} onClick={()=>void olderRecords()}>{paging?"Loading older evidence…":"Load older evidence"}</button>:null}</>:null}
 <div className="evidence-actions"><button type="button" className="secondary" aria-expanded={showCalculations} onClick={()=>setShowCalculations(!showCalculations)}>{showCalculations?"Hide calculated records":"Review calculated records over time"}</button></div>{showCalculations?<CalculationHistory/>:null}
 <section className="evidence-entry"><h2>Share evidence for review</h2><p>Select up to 50 current records from the same Lab and curriculum version. Sharing gives the assigned facilitator access to those selected records while your group membership and consent remain active. You can revoke access here.</p><EvidenceState {...sharing} retry={()=>void sharing.load()}/>{selectedRecords.length?<form className="evidence-form" onSubmit={e=>{e.preventDefault();void share();}}><p>{selectedRecords.length} records selected</p>{groups.length?<label>Group<select value={activeGroup} disabled={sharing.saving} onChange={e=>{setGroup(e.target.value);setChecked(false);setRequestKey(crypto.randomUUID());}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>:<p>No active group matches all these selected records. Choose current Lab evidence from one group’s curriculum.</p>}<label>Submission title<input required maxLength={200} disabled={sharing.saving} value={title} onChange={e=>{setTitle(e.target.value);setRequestKey(crypto.randomUUID());}}/></label><label className="assessment-acknowledgement"><input type="checkbox" checked={checked} disabled={sharing.saving} onChange={e=>setChecked(e.target.checked)}/><span>I choose to share these selected records with my group’s assigned facilitator for review.</span></label><button disabled={sharing.saving||!checked||!activeGroup||!title.trim()} type="submit">{sharing.saving?"Sharing evidence…":"Share selected evidence"}</button></form>:<p>Select eligible evidence above to start a submission.</p>}</section>
 <section className="evidence-entry"><h2>Submissions and facilitator reviews</h2>{sharing.data?.submissions.length?sharing.data.submissions.map(s=><article key={s.id} className="evidence-entry"><h3>{s.title}</h3><p className="evidence-meta">Shared {date(s.created_at)} · {s.evidence.length} records · {s.revoked_at?"Sharing revoked":s.current?"Available for group review":"Access inactive or evidence revised"}</p>{!s.revoked_at?<button className="secondary" type="button" disabled={sharing.saving} onClick={()=>void sharing.act({action:"revoke",submissionId:s.id})}>Revoke sharing: {s.title}</button>:null}<AssessmentHistory submission={s} rubrics={sharing.data!.rubrics}/></article>):<p>No evidence has been shared yet.</p>}</section></main>;
}
